import { ref } from "vue";
export const detailList = [
  {
    id: 1,
    customer: {
      name: "고윤정",
      mobile: "010-1234-1234",
      email: "yunjung@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "호시자키",
      package: "6회권",
      date: "2025-03-17 ~",
      count: "2회 / 6회",
      during: "3개월",
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025-05-15, 오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
      get total() {
        return (
          this.service +
          this.extra +
          this.coupon +
          this.membershipDiscount +
          this.extraDiscount
        );
      },
    },
  },
  {
    id: 3,
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
      get total() {
        return (
          this.service +
          this.extra +
          this.coupon +
          this.membershipDiscount +
          this.extraDiscount
        );
      },
    },
  },
  {
    id: 2,
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
      get total() {
        return (
          this.service +
          this.extra +
          this.coupon +
          this.membershipDiscount +
          this.extraDiscount
        );
      },
    },
  },
];
// 예약 내역 데이터
export const reservList = ref([
  {
    id: 1,
    number: "BING-2025-001",
    status: "confirmed",
    date: "2025-03-18, 오후 11시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025.03.17(월) 14:00",
  },
  {
    id: 2,
    number: "BING-2025-002",
    status: "assigned",
    date: "2025-05-15, 오후 11시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025.04.30(수) 16:00",
  },

  {
    id: 3,
    number: "BING-2025-003",
    status: "waiting",
    date: "2025-06-18, 오후 11시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025.06.17(화) 14:00",
  },
]);

// 전체 테이블 데이터
export const fullReservationList = [
  {
    id: 1,
    number: "BING-2025-001",
    status: "confirmed",
    date: "2025-03-18, 오후 11시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025.03.17(월) 14:00",
    customer: {
      name: "고윤정",
      mobile: "010-1234-1234",
      email: "yunjung@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "호시자키",
      package: "6회권",
      date: "2025-03-17 ~",
      count: "2회 / 6회",
      during: "3개월",
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025-05-15, 오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 2,
    number: "BING-2025-002",
    status: "waiting",
    date: "2025-06-18, 오후 11시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025.06.17(화) 14:00",
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 3,
    number: "BING-2025-003",
    status: "assigned",
    date: "2025-05-15, 오후 11시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025.04.30(수) 16:00",
    customer: {
      name: "김카페",
      mobile: "010-1245-1534",
      email: "cafekim@naver.com",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 4,
    number: "BING-2025-004",
    status: "confirmed",
    date: "2025-03-28, 오후 7시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-02-28",
    customer: {
      name: "정유진",
      mobile: "010-1234-1234",
      email: "정유진@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-25 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025-05-15, 오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 5,
    number: "BING-2025-005",
    status: "waiting",
    date: "2025-01-29, 오후 9시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-02-21",
    customer: {
      name: "박서준",
      mobile: "010-1245-1534",
      email: "박서준@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 6,
    number: "BING-2025-006",
    status: "assigned",
    date: "2025-02-22, 오후 10시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-03-04",
    customer: {
      name: "최지은",
      mobile: "010-1245-1534",
      email: "최지은@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 7,
    number: "BING-2025-007",
    status: "confirmed",
    date: "2025-02-12, 오후 3시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-01-20",
    customer: {
      name: "이동건",
      mobile: "010-1234-1234",
      email: "이동건@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-01-26 ~",
      count: "5회 / 6회",
      during: "3개월",
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025-05-15, 오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 8,
    number: "BING-2025-008",
    status: "waiting",
    date: "2025-01-05, 오후 1시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-03-21",
    customer: {
      name: "장민호",
      mobile: "010-1245-1534",
      email: "장민호@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-13 ~",
      count: "3회 / 6회",
      during: "6개월",
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 9,
    number: "BING-2025-009",
    status: "assigned",
    date: "2025-02-09, 오후 11시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-02-19",
    customer: {
      name: "하윤아",
      mobile: "010-1245-1534",
      email: "하윤아@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 10,
    number: "BING-2025-010",
    status: "confirmed",
    date: "2025-03-26, 오후 3시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-02-11",
    customer: {
      name: "문채원",
      mobile: "010-1234-1234",
      email: "문채원@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-22 ~",
      count: "6회 / 6회",
      during: "3개월",
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025-05-15, 오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 11,
    number: "BING-2025-011",
    status: "waiting",
    date: "2025-01-27, 오후 5시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-03-13",
    customer: {
      name: "윤도현",
      mobile: "010-1245-1534",
      email: "윤도현@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-02-04 ~",
      count: "3회 / 6회",
      during: "1개월",
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
  {
    id: 12,
    number: "BING-2025-012",
    status: "assigned",
    date: "2025-01-20, 오후 8시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-03-27",
    customer: {
      name: "백예린",
      mobile: "010-1245-1534",
      email: "백예린@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 13,
    number: "BING-2025-013",
    status: "confirmed",
    date: "2025-01-09, 오후 10시 이후",
    memo: "라벨 부착해주세요.",
    price: 0,
    reservdate: "2025-04-01",
    customer: {
      name: "서지호",
      mobile: "010-1234-1234",
      email: "서지호@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "스탠다드",
      package: "12회권",
      date: "2025-03-09 ~",
      count: "1회 / 6회",
      during: "3개월",
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: "기타 문의",
      title: "라벨 증정",
      memo: "라벨 안 주고 가셨어요 ㅠㅠ",
      file: null,
    },
    reservinfo: {
      type: "비정기 청소",
      machine: "[호시자키] 250kg 이상 1대",
      address: "대구광역시 중구 중앙대로 77길 22 스타벅스 종로점",
      date: "2025-05-15, 오후 11시 이후",
      plus: "자가점검키트",
      memo: "레포트 문자로 보내주세요",
    },
    payment: {
      service: 210000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: -210000,
      extraDiscount: -4900,
    },
    primemember: true,
  },
  {
    id: 14,
    number: "BING-2025-014",
    status: "waiting",
    date: "2025-01-18, 오후 11시 이후",
    memo: "세제 신청했어요 ~ ^^",
    price: 0,
    reservdate: "2025-03-06",
    customer: {
      name: "김지수",
      mobile: "010-1245-1534",
      email: "김지수@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: null,
      date: null,
      count: null,
      during: null,
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: "자가 점검 키트",
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 4900,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: false,
  },
  {
    id: 15,
    number: "BING-2025-015",
    status: "assigned",
    date: "2025-02-15, 오후 3시 이후",
    memo: "레포트 문자로 보내주세요",
    price: 0,
    reservdate: "2025-02-26",
    customer: {
      name: "강다현",
      mobile: "010-1245-1534",
      email: "강다현@bingfree.co.kr",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 5층",
    },
    membership: {
      name: "스탠다드",
      package: "6회권",
      date: "2025-01-04 ~",
      count: "5회 / 6회",
      during: "2개월",
    },
    worker: {
      name: "김기사",
      mobile: "010-4321-4321",
      email: "mrkim@bingfree.co.kr",
    },
    inquiry: {
      type: null,
      title: null,
      memo: null,
      file: null,
    },
    reservinfo: {
      type: "일회성 청소",
      machine: "[스탠다드] 50kg 미만 1대",
      address: "대구광역시 중구 동성로 3가 동성로 1길 15 4층",
      date: "2025-05-22, 오후 2시",
      plus: null,
      memo: null,
    },
    payment: {
      service: 99000,
      extra: 0,
      coupon: 0,
      membershipDiscount: 0,
      extraDiscount: 0,
    },
    primemember: true,
  },
];

// 테이블 헤더 데이터
export const TableHeaders = [
  { key: "item", label: "결제 내역" },
  { key: "amount", label: "결제금액" },
  { key: "date", label: "결제일" },
  { key: "period", label: "이용 기간" },
  { key: "status", label: "상태" },
  { key: "receipt", label: "영수증" },
];

// 테이블 내용 데이터
export const TableData = [
  {
    item: "호시자키(250kg~) 6회권",
    amount: "1,134,000원",
    date: "2025.03.17 14:00",
    period: "2025.03.17 ~ 2026.03.17",
    status: "결제 완료",
    receipt: "영수증 보기",
    receiptUrl: "#",
  },
];
